export const activities = [
  {
    type: "Sell",
    typeColor: "text-red-400",
    token: "WYD",
    tokenFull: "wyd in this slime",
    price: "0.9707",
    amount: "$31.4K",
    time: "2h",
  },
  {
    type: "Buy",
    typeColor: "text-teal-400",
    token: "WYD",
    tokenFull: "wyd in this slime",
    price: "0.9802",
    amount: "$31.7K",
    time: "2h",
  },
  {
    type: "Sell",
    typeColor: "text-red-400",
    token: "@?",
    tokenFull: "What's her @?",
    price: "1.1109",
    amount: "$79.9K",
    time: "2h",
  },
  {
    type: "Sell",
    typeColor: "text-red-400",
    token: "kodi",
    tokenFull: "kodi",
    price: "0.2063",
    amount: "$26.8K",
    time: "3h",
  },
  {
    type: "Buy",
    typeColor: "text-teal-400",
    token: "kodi",
    tokenFull: "kodi",
    price: "0.4948",
    amount: "$64.3K",
    time: "3h",
  },
  {
    type: "Sell",
    typeColor: "text-red-400",
    token: "@?",
    tokenFull: "What's her @?",
    price: "0.5102",
    amount: "$37.3K",
    time: "4h",
  },
];
