export const positions = [
  {
    token: "PWD",
    tokenFull: "pigeon",
    bought: "$449.98",
    boughtAmount: "42.8M PWD",
    sold: "$0",
    soldAmount: "0 PWD",
    remaining: "$210.57",
    remainingAmount: "42.8M PWD",
    pnl: "-$239.41 (-53.2%)",
    pnlColor: "text-red-500",
  },
  {
    token: "USDC",
    tokenFull: "USD Coin",
    bought: "$0",
    boughtAmount: "0 USDC",
    sold: "$299.03",
    soldAmount: "300 USDC",
    remaining: "$0.01",
    remainingAmount: "0.01 USDC",
    pnl: "+$299.03 (+Infinity%)",
    pnlColor: "text-green-500",
  },
  {
    token: "TRENCHER",
    tokenFull: "trencher",
    bought: "$0",
    boughtAmount: "0 TRENCHER",
    sold: "$0",
    soldAmount: "0 TRENCHER",
    remaining: "$0",
    remainingAmount: "14.6K TRENCHER",
    pnl: "+$0 (+NaN%)",
    pnlColor: "text-green-500",
  },
];
