# Generated by Django 4.2.18 on 2025-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='default_currency',
            field=models.CharField(default='OMR', max_length=3),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
