# Generated by Django 4.2.18 on 2025-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='work_email',
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the organization user'),
        ),
    ]
