# Generated by Django 4.2.18 on 2025-01-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_remove_organization_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('hr', 'HR'), ('focal_point', 'Focal Point')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.applicant'),
        ),
    ]
