version: '3'

services:
  web:
    build: .
    command: python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://mysite:mysite@db:5432/mysite
      - SECRET_KEY=${SECRET_KEY}
      - WEB_CONCURRENCY=4

volumes:
  postgres_data: