name: CI Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: backend
      run: npm ci

    - name: Run linter
      working-directory: backend
      run: npm run lint

    - name: Run tests
      working-directory: backend
      env:
        DATABASE_URL: postgresql://postgres:example@localhost:5432/test
        JWT_SECRET: test-secret
        JWT_ISSUER: test-issuer
        HEALTH_TOKEN: test-token
      run: npx jest --config=jest.json

    - name: Build
      working-directory: backend
      run: npm run build
