name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t react-app ./frontend

      - name: Create deployment package
        run: tar -cvf ./frontend/react-app.tar -C ./frontend .

      - name: Push image to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./frontend/react-app.tar
          target: ~/react-app

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu ~/react-app
            docker stop react-app || true
            docker rm react-app || true
            tar -xvf ~/react-app/react-app.tar -C ~/react-app
            docker build -t react-app ~/react-app
            docker run -d --name react-app -p 8080:80 react-app
